name: youth_club_app
description: A Flutter application for youth club community and inspiration.
version: 1.0.6+6

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Services
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  firebase_auth: ^4.15.3
  firebase_database: ^10.4.0
  
  # UI & UX
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.4
  
  # Google Services
  google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  firebase_auth_mocks: ^0.13.0
  fake_cloud_firestore: ^2.4.1+1
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
